/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.User;
import model.Recipe;
import db.DBUtil;
import util.SerializationUtil;
import thread.ReminderThread;
import view.MainMenuForm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;

/**
 *
 * @author LENOVO
 */
public class RecipeForm extends javax.swing.JFrame {

    private User currentUser;
    private boolean isEditMode = false;
    private Recipe currentRecipe;
    private File selectedImageFile;
    private String existingImageFileName; // menyimpan nama gambar lama jika edit

    /**
     * Creates new form RecipeForm
     */
    public RecipeForm(User user) {
        initComponents();

        this.setSize(600, 700);              // ukuran tetap
        this.setLocationRelativeTo(null);   // di tengah layar
        this.setResizable(false);           // tidak bisa resize

        this.currentUser = user;

        // isi combo box
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Sarapan", "Makan Siang", "Makan Malam", "Cemilan", "Minuman", "Dessert", "Lainnya"
        }));

        cmbDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Mudah", "Sedang", "Sulit"
        }));
    }

    public RecipeForm(User user, Recipe recipeToEdit) {
        this(user); // panggil constructor utama
        this.isEditMode = true;
        this.currentRecipe = recipeToEdit;

        // Isi data ke form
        txtTitle.setText(recipeToEdit.getTitle());
        cmbCategory.setSelectedItem(recipeToEdit.getCategory());
        txtIngredients.setText(recipeToEdit.getIngredients());
        txtSteps.setText(recipeToEdit.getSteps());
        spnDuration.setValue(recipeToEdit.getDuration());
        cmbDifficulty.setSelectedItem(recipeToEdit.getDifficulty());

        existingImageFileName = recipeToEdit.getImageFileName(); // ⬅ Tambahan
        lblPreviewGambar.setText(existingImageFileName);         // ⬅ Tambahan

        lblTambahResep.setText("Edit Resep");
        btnSimpan.setText("Update");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTambahResep = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        spnDuration = new javax.swing.JSpinner();
        cmbDifficulty = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIngredients = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSteps = new javax.swing.JTextArea();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblIngredients = new javax.swing.JLabel();
        lblSteps = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        lblDifficulty = new javax.swing.JLabel();
        lblPreviewGambar = new javax.swing.JLabel();
        btnPilihGambar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(143, 179, 226));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 700));

        jPanel2.setBackground(new java.awt.Color(30, 46, 79));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/resep logo.png"))); // NOI18N
        jLabel2.setText(" ");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ChefNote");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTambahResep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTambahResep.setText("Tambah Resep");

        txtTitle.setText(" ");
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sarapan", "Makan Siang", "Makan Malam", "Cemilan", "Minuman", "Dessert", "Sup" }));

        spnDuration.setModel(new javax.swing.SpinnerNumberModel(1, 1, 300, 5));

        cmbDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mudah", "Sedang", "Sulit" }));

        txtIngredients.setColumns(20);
        txtIngredients.setRows(5);
        jScrollPane1.setViewportView(txtIngredients);

        txtSteps.setColumns(20);
        txtSteps.setRows(5);
        jScrollPane3.setViewportView(txtSteps);

        btnBatal.setText("Kembali");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        lblTitle.setText("Judul Resep :");

        lblIngredients.setText("Bahan - bahan :");

        lblSteps.setText("Langkah - langkah :");

        lblCategory.setText("Category : ");

        lblDuration.setText("Durasi :");

        lblDifficulty.setText("Kesulitan :");

        lblPreviewGambar.setText(" ");

        btnPilihGambar.setText("Pilih Gambar");
        btnPilihGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihGambarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSteps)
                            .addComponent(lblIngredients)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPilihGambar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPreviewGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle)
                                    .addComponent(lblCategory)
                                    .addComponent(lblDifficulty)
                                    .addComponent(lblDuration))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnDuration, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbCategory, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbDifficulty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(lblTambahResep)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTambahResep)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDifficulty))
                .addGap(18, 18, 18)
                .addComponent(lblIngredients)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSteps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnSimpan)
                    .addComponent(lblPreviewGambar)
                    .addComponent(btnPilihGambar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String title = txtTitle.getText().trim();
        String category = cmbCategory.getSelectedItem().toString();
        String ingredients = txtIngredients.getText().trim();
        String steps = txtSteps.getText().trim();
        int duration = (int) spnDuration.getValue();
        String difficulty = cmbDifficulty.getSelectedItem().toString();

        if (title.isEmpty() || ingredients.isEmpty() || steps.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi.");
            return;
        }

        try (Connection conn = DBUtil.getConnection()) {
            String imageFileName;

            if (selectedImageFile != null) {
                imageFileName = selectedImageFile.getName();
            } else if (isEditMode) {
                imageFileName = existingImageFileName;
            } else {
                JOptionPane.showMessageDialog(this, "Silakan pilih gambar terlebih dahulu.");
                return;
            }

            if (isEditMode && currentRecipe != null) {
                // MODE UPDATE
                String sql = "UPDATE recipes SET title = ?, category = ?, ingredients = ?, steps = ?, duration = ?, difficulty = ?, image_file_name = ? WHERE id = ? AND user_id = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, title);
                ps.setString(2, category);
                ps.setString(3, ingredients);
                ps.setString(4, steps);
                ps.setInt(5, duration);
                ps.setString(6, difficulty);
                ps.setString(7, imageFileName);
                ps.setInt(8, currentRecipe.getId());
                ps.setInt(9, currentUser.getId());

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "✅ Resep berhasil diperbarui.");
                this.dispose();
                new LihatResepForm(currentUser).setVisible(true);

            } else {
                // MODE TAMBAH
                String sql = "INSERT INTO recipes (user_id, title, category, ingredients, steps, duration, difficulty, image_file_name) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, currentUser.getId());
                ps.setString(2, title);
                ps.setString(3, category);
                ps.setString(4, ingredients);
                ps.setString(5, steps);
                ps.setInt(6, duration);
                ps.setString(7, difficulty);
                ps.setString(8, imageFileName); // mungkin typo sebelumnya pakai setInt, harusnya string
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "✅ Resep berhasil disimpan.");

                // Reset form
                txtTitle.setText("");
                txtIngredients.setText("");
                txtSteps.setText("");
                spnDuration.setValue(1);
                cmbCategory.setSelectedIndex(0);
                cmbDifficulty.setSelectedIndex(0);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Gagal menyimpan resep: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        new MainMenuForm(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnPilihGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihGambarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            selectedImageFile = fileChooser.getSelectedFile();

            // Cek apakah gambar valid (opsional)
            if (!selectedImageFile.getName().toLowerCase().matches(".*\\.(jpg|jpeg|png|gif)$")) {
                JOptionPane.showMessageDialog(this, "File gambar harus JPG, PNG, atau GIF.");
                selectedImageFile = null;
                return;
            }

            // Tampilkan nama file di label preview
            lblPreviewGambar.setText(selectedImageFile.getName());

            // Salin gambar ke folder /src/view/images/
            File targetDir = new File("view.images/");
            if (!targetDir.exists()) {
                targetDir.mkdirs();
            }

            File targetFile = new File(targetDir, selectedImageFile.getName());
            try {
                Files.copy(selectedImageFile.toPath(), targetFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan gambar: " + e.getMessage());
                selectedImageFile = null;
            }
        }
    }//GEN-LAST:event_btnPilihGambarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnPilihGambar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbDifficulty;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDifficulty;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblIngredients;
    private javax.swing.JLabel lblPreviewGambar;
    private javax.swing.JLabel lblSteps;
    private javax.swing.JLabel lblTambahResep;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSpinner spnDuration;
    private javax.swing.JTextArea txtIngredients;
    private javax.swing.JTextArea txtSteps;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
